### ISSUE TITLE
hsl() may be broken

### ISSUE THREAD

**Issue by Frikki** [typestyle/csx#36]
**Version: csx@8.5.0**

Here is a screenshot from photoshop showing the color codes for a particular blue.

<img width="116" alt="screen shot 2018-04-16 at 12 52 17 pm" src="https://user-images.githubusercontent.com/180569/38805147-14e6f078-4175-11e8-84f0-9dadd4810440.png">

If I use the HSL values with CSX, I get a wrong output when I call `toHexString()`.

```typescript
// Outputs: #D6E4FF (Wrong!)
export const blueHsl = hsl(220, 1, 0.92).toHexString()

// Outputs: #004EEB (Correct!)
export const blueRgb = rgb(0, 78, 235).toHexString()
```

**Comment by notoriousb1t** [comment]
HSB (HSV) is a different color space than HSL.  😄 

When I was creating the ColorHelper initially, I thought about adding in every color space, but the math to go between all the color spaces would have bloated the library.  Since web only supports HSL and RGB, I decided that was a good line to draw.

**Comment by Frikki** [comment]
Ah, I see. My bad. Thanks for clearing this up. I’m closing the issue.
