### ISSUE TITLE
css('colorName') always return 'rgb(255, 0, 0)'

### ISSUE THREAD

**Issue by zheeeng** [typestyle/csx#46]
version: 9.0.0

```
  console.log(csx.color('red').toString())
  console.log(csx.color('green').toString())
  console.log(csx.color('blue').toString())
````

output:

```
rgb(255,0,0)
rgb(255,0,0)
rgb(255,0,0)
```

**Comment by notoriousb1t** [comment]
We removed named colors in 9.0.0 because they increased the bundle size of the library substantially and because it appeared that no one was using them. (there are well over 100 named colors) There was discussion about making them an optional import, but I was concerned about over-complicating a helper library.

The reason it shows up as red is because that is the default color we assign when the color cannot be parsed.

**Comment by notoriousb1t** [comment]
I apologize that the docs don't reflect this.  I am marking this as docs so we can go back and remedy that.

**Comment by zheeeng** [comment]
Thx for your reply.
