### ISSUE TITLE
merge hsl and hsla into one function

### ISSUE THREAD

**Issue by xialvjun** [typestyle/csx#87]
```ts
/**
 * Creates a color from hue, saturation, and lightness.  Alpha is automatically set to 100%
 */
export declare function hsl(hue: number, saturation: string | number, lightness: string | number): ColorHelper;
/**
 * Creates a color from hue, saturation, lightness, and alpha
 */
export declare function hsla(hue: number, saturation: string | number, lightness: string | number, opacity: string | number): ColorHelper;


// merge them into one function... Same is rgb and rgba...
export declare function hsla(hue: number, saturation: string | number, lightness: string | number, opacity?: string | number): ColorHelper;
```

**Comment by notoriousb1t** [comment]
If these were to be merged, I think it would make sense to merge them into hsl rather than hsla since that matches the functional notation of HSL. I am open to a PR for this if you want to contribute one (which I will approve quickly), but I don't have have a lot of time allotted to OSS this month, so otherwise, it might be a few weeks until I can get to this change.

Let me know if you want to do a PR for it, the same goes for doing so for RGB.

**Comment by notoriousb1t** [comment]
Actually, I have another ticket in CSX to push out, so I will address this shortly.

**Comment by notoriousb1t** [comment]
Added in 697dd6362a1c7bdd18873d76ca0e99cc5191ac41. I will close this when I am able to roll out those changes.

**Comment by notoriousb1t** [comment]
This was published in https://github.com/typestyle/csx/releases/tag/v10.0.0. Please take a look and let me know if that works for you.

**Comment by xialvjun** [comment]
Yeah, thanks.
